name: Build

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    name: Build:Web
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Inject Variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Install Dependencies
      run: npm ci
    - name: Build Artifact
      run: npm run build
    - name: Deploy Artifact
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        CLEAN: true
        BRANCH: gh-pages
        FOLDER: builds/web
        COMMIT_MESSAGE: Deploying ${{ github.sha }}
        ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
  test:
    name: Test:Function
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node Environment
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Install Dependencies
      run: npm ci
    - name: Perform Lint
      run: npm run lint
    - name: Perform Tests
      run: npm run test
      env:
        FORCE_COLOR: true
